"""Generate static catalog/detail pages from one manifest and the actual preview source."""
from pathlib import Path
from html import escape as e
import json
import xml.etree.ElementTree as ET
root=Path(__file__).resolve().parents[1]
dist=root/'dist'
catalog=json.loads((root/'showcase/catalog.json').read_text())
items=catalog['items']; version=catalog['version']; base='https://www.rayden-ui.dev'
counts={kind:sum(i['type']==kind for i in items) for kind in ['blocks','components']}
by_name={item['export']:item for item in items}
def path(item):return f"/{item['type']}/{item['slug']}"
def head(title,description,url,schema):
 return f'''<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#101011"><title>{e(title)} | Rayden UI</title><meta name="description" content="{e(description)}"><link rel="canonical" href="{base}{url}"><meta name="robots" content="index, follow, max-image-preview:large"><meta property="og:type" content="website"><meta property="og:site_name" content="Rayden UI"><meta property="og:title" content="{e(title)}"><meta property="og:description" content="{e(description)}"><meta property="og:url" content="{base}{url}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="{e(title)}"><meta name="twitter:description" content="{e(description)}"><link rel="icon" href="/assets/rayden-mark.svg" type="image/svg+xml"><link rel="preload" href="/assets/manrope-latin-normal.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/fonts.css"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/explore.css"><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script><script src="/explore.js" defer></script></head><body><a class="skip-link" href="#main">Skip to content</a><header class="nav-shell"><nav class="nav explore-container" aria-label="Main navigation"><a class="brand" href="/" aria-label="Rayden UI home"><img src="/assets/rayden-logo.svg" alt="Rayden" width="241" height="99"></a><div class="explore-nav"><a href="/explore?type=components">Components</a><a href="/explore?type=blocks">Blocks</a><a href="/guides/rayden-ai">For AI</a><a href="https://rayden-docs.vercel.app/">Documentation ↗</a></div></nav></header>'''
def footer():
 return '''<footer class="explore-container"><div class="footer-top"><a class="brand" href="/" aria-label="Rayden UI home"><img src="/assets/rayden-logo.svg" alt="Rayden" width="241" height="99"></a><p>Open-source React UI, built with care.</p><div><a href="/#guides">Guides</a><a href="https://rayden-docs.vercel.app/">Docs</a><a href="https://github.com/playbookTV/Rayden">GitHub</a></div></div><div class="footer-bottom"><span>© 2026 Rayden UI</span><span>Open source. Open possibilities.</span><a href="#main">Back to top ↑</a></div></footer><p class="sr-only" id="showcase-status" role="status"></p></body></html>'''
def tag(item): return '<span class="library-tag">Experimental</span>' if item['type']=='blocks' else ''
def thumb(item,index):
 return f'''<article class="library-card" data-type="{item['type']}" data-category="{item['category']}" data-search="{e((item['name']+' '+item['export']+' '+item['category']+' '+item['description']).lower())}"><a href="{path(item)}"><div class="library-thumb"><picture><source media="(max-width:520px)" srcset="/assets/showcase/{item['slug']}-mobile.png"><img src="/assets/showcase/{item['slug']}.png" alt="{e(item['name'])} rendered with Rayden UI {version}" width="900" height="560" loading="{'eager' if index<2 else 'lazy'}"></picture><span class="library-open">Open preview ↗</span></div><div class="library-card-title"><h2>{e(item['name'])}</h2>{tag(item)}</div><p>{e(item['description'])}</p></a></article>'''
collection={'@context':'https://schema.org','@type':'CollectionPage','name':'Explore Rayden UI components and blocks','url':base+'/explore','description':'Browse real React components and complete UI blocks, try their interactions, and copy working examples.','mainEntity':{'@type':'ItemList','itemListElement':[{'@type':'ListItem','position':i+1,'name':item['name'],'url':base+path(item)} for i,item in enumerate(items)]}}
categories=['All examples']+list(dict.fromkeys(i['category'] for i in items))
filters=''.join(f'<button type="button" data-category-filter="{e(c)}" aria-pressed="{str(c=="All examples").lower()}"><span>{e(c)}</span><small data-category-count="{e(c)}"></small></button>' for c in categories)
options=''.join(f'<option value="{e(c)}">{e(c)}</option>' for c in categories)
page=head('Explore React components & UI blocks',collection['description'],'/explore',collection)+f'''
<main id="main" class="explore-container" data-catalog><div class="library-heading"><div><p class="library-kicker">THE RAYDEN LIBRARY</p><h1>Find your next building block.</h1><p>Real components. Complete patterns. A closer look at what you can build.</p></div><span class="library-version">{len(items)} working examples · v{version}</span></div>
<div class="library-toolbar"><div class="library-switch" role="group" aria-label="Example type"><button type="button" data-type-filter="blocks" aria-pressed="true">Blocks <small>{counts["blocks"]:02d}</small></button><button type="button" data-type-filter="components" aria-pressed="false">Components <small>{counts["components"]:02d}</small></button></div><label class="library-search"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><input type="search" id="library-search" placeholder="Find your next piece…" aria-label="Search components and blocks"></label></div>
<div class="library-layout"><aside class="library-sidebar"><h2>CATEGORIES</h2><div role="group" aria-label="Filter by category">{filters}</div><p class="library-sidebar-note">Built from the published library.<br>Try it. Inspect it. Make it yours.</p></aside><div><label class="library-mobile-filter">Category<select id="mobile-category">{options}</select></label><p class="library-results" id="library-results" role="status">Choose a block or component to explore.</p><noscript><p>All examples are listed below. Enable JavaScript to search and filter.</p></noscript><div class="library-grid">{''.join(thumb(item,index) for index,item in enumerate(items))}</div><div class="library-empty" id="library-empty" hidden><h2>No matching examples.</h2><p>Try a shorter search or choose another category.</p><button class="showcase-button" id="clear-filters">Clear search and filters</button></div></div></div></main>'''+footer()
(dist/'explore.html').write_text(page)
for item in items:
 url=path(item); name=item['name']; slug=item['slug']; is_block=item['type']=='blocks'
 schema={'@context':'https://schema.org','@graph':[{'@type':'WebPage','name':name+' — React '+('UI block' if is_block else 'component'),'url':base+url,'description':item['description'],'isPartOf':{'@type':'CollectionPage','url':base+'/explore','name':'Explore Rayden UI'},'mainEntity':{'@type':'SoftwareSourceCode','name':item['export']+' usage example','programmingLanguage':['TypeScript','React'],'codeSampleType':'full','runtimePlatform':f'@raydenui/ui {version}','license':'https://github.com/playbookTV/Rayden/blob/main/LICENSE'}},{'@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Explore','item':base+'/explore'},{'@type':'ListItem','position':2,'name':name,'item':base+url}]}]}
 code=(root/f'preview/src/examples/{slug}.tsx').read_text()
 built=''.join(f'<a href="{path(by_name[n])}">{e(n)}</a>' for n in item.get('builtWith',[]) if n in by_name)
 built_section=f'<h2>Built with</h2><div class="detail-built">{built}</div>' if built else ''
 states=''.join(f'<option value="{s}">{s.capitalize()}</option>' for s in item['states'])
 state_control=f'<label>State<select id="preview-state">{states}</select></label>' if len(item['states'])>1 else ''
 import_path='@raydenui/ui/blocks' if is_block else '@raydenui/ui'
 install=f'npm install @raydenui/ui@{version}\n\nimport {{ {item["export"]} }} from "{import_path}";\nimport "@raydenui/ui/styles.css";'
 prompt=f'Use @raydenui/ui@{version} to build an interface based on this {name} example. Import {item["export"]} from {import_path}. Preserve real supported props and the explicit demo behaviour. If Rayden MCP is available, check its reference UI version first and use only guidance it actually supports; do not assume it has a contract for every block. Review the following complete example, adapt it to my project, and run the build and interaction checks.'
 related=sorted([i for i in items if i['type']==item['type'] and i!=item], key=lambda candidate:candidate['category']!=item['category'])[:3]
 page=head(name+' — React '+('UI block' if is_block else 'component'),item['description'],url,schema)+f'''
<main id="main" class="explore-container" data-detail="{slug}"><nav class="detail-breadcrumb" aria-label="Breadcrumb"><a data-back href="/explore?type={item['type']}">← Explore {item['type']}</a><span>/</span><span aria-current="page">{e(name)}</span></nav><div class="detail-heading"><div><p class="library-kicker">{item['category'].upper()} · {'BLOCK' if is_block else 'COMPONENT'}</p><h1>{e(name)}</h1><p class="detail-description">{e(item['description'])}</p><div class="detail-meta"><span>@raydenui/ui {version}</span>{tag(item)}<span>React + TypeScript</span></div></div><div class="detail-actions"><button class="showcase-button" data-copy-target="example-code" data-ai-prompt="{e(prompt)}">Copy for AI ↗</button><a class="showcase-button primary" href="https://rayden-docs.vercel.app/{item['type']}/{item['docs']}">Documentation ↗</a></div></div>
<div class="preview-workbench"><div class="preview-toolbar"><div class="library-switch" role="group" aria-label="Example view"><button type="button" data-view="preview" aria-pressed="true" aria-controls="preview-panel">Preview</button><button type="button" data-view="code" aria-pressed="false" aria-controls="code-panel">Code</button></div><div class="preview-options" id="preview-options">{state_control}<label>Theme<select id="preview-theme"><option value="light">Light</option><option value="dark">Dark</option></select></label><label>Viewport<select id="preview-viewport"><option value="desktop">Fit</option><option value="tablet">Tablet</option><option value="mobile">Mobile</option></select></label><button class="preview-reset" id="preview-reset" type="button">↺ Reset preview</button></div></div><div id="preview-panel"><div class="preview-failure" id="preview-failure" role="alert" hidden>The preview couldn’t load. Try Reset preview, or open Code to use the example.</div><div class="preview-surface"><div class="preview-loading" id="preview-loading" role="status">Loading the real component…</div><div class="preview-frame-wrap" id="preview-frame-wrap" data-viewport="desktop"><iframe id="live-preview" title="Interactive {e(name)} example" height="{item['height']}" sandbox="allow-scripts allow-same-origin" data-example="{slug}"></iframe></div></div><noscript><p>Enable JavaScript to interact with this example. The full source is available below.</p></noscript></div><div class="preview-code" id="code-panel"><button class="showcase-button" data-copy-target="example-code">Copy code</button><pre tabindex="0" aria-label="{e(name)} example source"><code id="example-code">{e(code)}</code></pre></div><div class="preview-note"><span>Live library components · illustrative demo data · no remote submissions</span><span>Reset returns to the initial example.</span></div></div>
<div class="detail-information"><div><h2>Made for real interfaces.</h2><p>{e(item['detail'])}</p><h2>Try it</h2><p>{e(item['try'])}</p>{built_section}</div><aside><div class="detail-install"><h2>Add it to your React app</h2><pre id="install-code">{e(install)}</pre><button class="showcase-button" data-copy-target="install-code">Copy setup</button></div><p style="margin-top:20px;font-size:13px">The Code tab contains the full preview component. Import the stylesheet once in your app. Preview state changes reset local data. {'This block is experimental; review its documented limitations before using it in your product.' if is_block else 'Check keyboard interaction and application-specific behaviour in your own project.'}</p></aside></div>
<section class="showcase-related"><h2>A few more possibilities.</h2><div>{''.join(f'<a class="showcase-button" href="{path(i)}">{e(i["name"])} ↗</a>' for i in related)}</div></section></main>'''+footer()
 (dist/url.lstrip('/')).with_suffix('.html').write_text(page)
# Keep the sitemap's existing pages and their dates; update only changed catalog pages.
sitemap=dist/'sitemap.xml'; ns='http://www.sitemaps.org/schemas/sitemap/0.9'
tree=ET.fromstring(sitemap.read_text()); existing={node.find(f'{{{ns}}}loc').text:node.find(f'{{{ns}}}lastmod').text for node in tree}
existing[base+'/']='2026-09-24'
for route in ['/explore']+[path(i) for i in items]: existing[base+route]='2026-09-24'
sitemap.write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="'+ns+'">\n'+''.join(f'  <url><loc>{e(url)}</loc><lastmod>{date}</lastmod></url>\n' for url,date in existing.items())+'</urlset>\n')
llms=dist/'llms.txt'; text=llms.read_text(); start='## Interactive showcase\n'
section=start+'- [Explore components and blocks]('+base+'/explore): A curated gallery of '+str(len(items))+' examples rendered from published @raydenui/ui '+version+'. Block entries are labelled experimental.\n'+''.join(f'- [{i["name"]}]({base}{path(i)}): {i["description"]}\n' for i in items)+'\n'
if start in text:
 before,after=text.split(start,1); next_section=after.find('\n## '); text=before+section+(after[next_section+1:] if next_section!=-1 else '')
else: text=text.replace('## Practical guides',section+'## Practical guides')
llms.write_text(text)
print(f'Built catalog and {len(items)} detail pages with matching example source, sitemap and AI index.')
