export default {
  index: "Overview",
  "-- navigation": {
    type: "separator",
    title: "Navigation & shells",
  },
  "header-block": "HeaderBlock",
  "application-shell-block": "ApplicationShellBlock",
  "page-header-block": "PageHeaderBlock",
  "workspace-switcher-block": "WorkspaceSwitcherBlock",
  "command-palette-block": "CommandPaletteBlock",
  "site-footer-block": "SiteFooterBlock",
  navigation: "Application chrome",
  "-- application": {
    type: "separator",
    title: "Application UI",
  },
  "login-block": "LoginBlock",
  "create-account-block": "CreateAccountBlock",
  "kpi-overview-block": "KpiOverviewBlock",
  "table-block": "TableBlock",
  "searchable-table-block": "SearchableTableBlock",
  "profile-settings-block": "ProfileSettingsBlock",
  "notifications-block": "NotificationsBlock",
  "task-list-block": "TaskListBlock",
  "empty-state-block": "EmptyStateBlock",
  "-- marketing": {
    type: "separator",
    title: "Marketing & conversion",
  },
  "product-hero-block": "ProductHeroBlock",
  "feature-overview-block": "FeatureOverviewBlock",
  "pricing-plans-block": "PricingPlansBlock",
  "-- commerce": {
    type: "separator",
    title: "Commerce",
  },
  "product-collection-block": "ProductCollectionBlock",
  "product-detail-block": "ProductDetailBlock",
  "shopping-cart-block": "ShoppingCartBlock",
  "checkout-review-block": "CheckoutReviewBlock",
  commerce: "Commerce journey",
  "-- finance": {
    type: "separator",
    title: "Finance & billing",
  },
  "quick-send-block": "QuickSendBlock",
  "recent-transactions-block": "RecentTransactionsBlock",
  "account-balance-block": "AccountBalanceBlock",
  "transfer-review-block": "TransferReviewBlock",
  "invoice-detail-block": "InvoiceDetailBlock",
  "subscription-billing-block": "SubscriptionBillingBlock",
};
