export default {
  index: "Overview",
  button: "Button",
  "button-group": "ButtonGroup",
  input: "Input",
  select: "Select",
  "form-control": "FormControl",
  chip: "Chip",
  "file-upload": "FileUpload",
  tabs: "Tabs",
  breadcrumb: "Breadcrumb",
  pagination: "Pagination",
  "sidebar-menu": "SidebarMenu",
  "dropdown-menu": "DropdownMenu",
  table: "Table",
  avatar: "Avatar",
  "activity-feed": "ActivityFeed",
  "metrics-card": "MetricsCard",
  icon: "Icon",
  "empty-state-illustration": "EmptyStateIllustration",
  alert: "Alert",
  badge: "Badge",
  "progress-bar": "ProgressBar",
  "progress-circle": "ProgressCircle",
  tooltip: "Tooltip",
  divider: "Divider",
};
